parserOptions:
  ecmaFeatures: {jsx: false}
parser: babel-eslint
env:
  browser: true
  es6: true
  jquery: true
  node: true
extends: 'eslint:recommended'
rules:
  brace-style: [2, 1tbs]
  camelcase: 0
  comma-dangle: 0
  comma-style: [0, first]
  default-case: 0
  eol-last: 0
  func-style: [1, declaration, {allowArrowFunctions: true}]
  guard-for-in: 2
  indent: [2, 4, {SwitchCase: 1}]
  key-spacing: [1]
  keyword-spacing: [1, {after: true}]
  no-console: 0
  no-floating-decimal: 2
  no-mixed-requires: 1
  no-multi-spaces: 1
  no-nested-ternary: 2
  no-process-exit: 1
  no-shadow: 1
  no-trailing-spaces: 1
  no-undefined: 1
  no-underscore-dangle: 0
  no-unused-vars: 1
  quotes: [0, single]
  radix: 1
  semi: 1
  space-before-blocks: 1
  space-before-function-paren: [1, never]
  spaced-comment: [1, always, {exceptions: ['-']}]
  strict: 0
  valid-jsdoc: [1, {prefer: {return: returns}}]
  wrap-iife: 2
globals:
  after: false
  afterEach: false
  before: false
  beforeEach: false
  describe: false
  expect: false
  it: false
  xit: false
